### ISSUE TITLE
Playing multiple videos on one page

### ISSUE THREAD

**Issue by thaliamontreux** [vdalex25/rtsp-to-web-player#2]
I have been figuring out how to have multiple instances of this player on the same page and be able to have multiple streams playing at the same time basically on the same page. Is there any way to do this? I have not found a way how to contact you correctly so please if you can help please get a hold of me

**Comment by vdalex25** [comment]
added example in readme https://github.com/vdalex25/rtsp-to-web-player#usage-multiple-players
